name: lawyearn
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.3.3 <4.0.0"

dependencies:
  cached_network_image: ^3.3.1
  carousel_slider: ^4.2.1
  cupertino_icons: ^1.0.8
  dots_indicator: ^3.0.0
  equatable: ^2.0.5
  expandable_page_view: ^1.0.17
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.5
  flutter_screenutil: ^5.9.0
  flutter_svg: ^2.0.10+1
  fpdart: ^1.1.0
  get_it: ^7.7.0
  google_sign_in: ^6.2.1
  http: ^1.2.1
  image_picker: ^1.1.1
  loading_animation_widget: ^1.2.1
  rxdart: ^0.27.7
  smooth_page_indicator: ^1.1.0
  supabase_flutter: ^2.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.13.1
  mockito: ^5.4.4
  mocktail: ^1.0.3
  build_runner: ^2.4.9

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/socials/
    - assets/images/search/

  fonts:
    - family: Rubik
      fonts:
        - asset: assets/fonts/Rubik-Regular.ttf
    - family: Lugrasimo
      fonts:
        - asset: assets/fonts/Lugrasimo-Regular.ttf
    - family: PTSerif
      fonts:
        - asset: assets/fonts/PTSerif-Regular.ttf

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.png"
  min_sdk_android: 21
